name: smart_pharmacist
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.10.0

  # Future dependencies for speech recognition can be added here

flutter:
  uses-material-design: true
